Diagram:
  DefinitionFiles:
    - Type: URL
      Url: "https://raw.githubusercontent.com/awslabs/diagram-as-code/main/definitions/definition-for-aws-icons-light.yaml"

  Resources:
    Canvas:
      Type: AWS::Diagram::Canvas
      Direction: vertical
      Children:
        - AWSCloud
        - CloudFront
        - User

    User:
      Type: AWS::Diagram::Resource
      Preset: User
      Title: "User"

    CloudFront:
      Type: AWS::Diagram::Resource
      Preset: "Amazon CloudFront"
      Title: "Amazon CloudFront"

    AWSCloud:
      Type: AWS::Diagram::Cloud
      Direction: horizontal
      Preset: AWSCloudNoLogo
      Align: center
      Children:
        - VPC
        - ECR
        - SecretsManager
        - CloudWatch
        - SNS

    ECR:
      Type: AWS::ECR
      Title: "Amazon ECR"

    SecretsManager:
      Type: AWS::SecretsManager::Secret
      Title: "AWS Secrets Manager"

    CloudWatch:
      Type: AWS::CloudWatch
      Title: "Amazon CloudWatch"

    SNS:
      Type: AWS::SNS::Topic
      Title: "Amazon SNS"

    VPC:
      Type: AWS::EC2::VPC
      Title: "VPC"
      Direction: vertical
      Children:
        - PrivateSubnets
        - PublicSubnet
      BorderChildren:
        - Position: S
          Resource: IGW

    IGW:
      Type: AWS::EC2::InternetGateway
      IconFill:
        Type: rect

    PublicSubnet:
      Type: AWS::EC2::Subnet
      Preset: PublicSubnet
      Title: "Public Subnet"
      Children:
        - ALB

    ALB:
      Type: AWS::ElasticLoadBalancingV2::LoadBalancer
      Preset: "Application Load Balancer"
      Title: "Application Load Balancer"

    PrivateSubnets:
      Type: AWS::Diagram::HorizontalStack
      Children:
        - WebSubnet
        - DBSubnet

    WebSubnet:
      Type: AWS::EC2::Subnet
      Preset: PrivateSubnet
      Title: "Private Subnet (Web)"
      Children:
        - WebASG

    WebASG:
      Type: AWS::AutoScaling::AutoScalingGroup
      Preset: "AWS::AutoScaling::AutoScalingGroup"
      Title: "Auto Scaling Group"

    DBSubnet:
      Type: AWS::EC2::Subnet
      Preset: PrivateSubnet
      Title: "Private Subnet (DB)"
      Children:
        - RDSInstance

    RDSInstance:
      Type: AWS::RDS::DBInstance
      Title: "Amazon RDS"

  Links:
    - Source: User
      SourcePosition: N
      Target: CloudFront
      TargetPosition: S
      TargetArrowHead:
        Type: Open
      Type: orthogonal
    - Source: CloudFront
      SourcePosition: N
      Target: IGW
      TargetPosition: S
      TargetArrowHead:
        Type: Open
      Type: orthogonal
    - Source: IGW
      SourcePosition: N
      Target: ALB
      TargetPosition: S
      TargetArrowHead:
        Type: Open
      Type: orthogonal
    - Source: ALB
      SourcePosition: N
      Target: WebASG
      TargetPosition: S
      TargetArrowHead:
        Type: Open
      Type: orthogonal
    - Source: WebASG
      SourcePosition: E
      Target: RDSInstance
      TargetPosition: W
      TargetArrowHead:
        Type: Open
      Type: orthogonal
    - Source: WebASG
      SourcePosition: E
      Target: SecretsManager
      TargetPosition: W
      TargetArrowHead:
        Type: Open
      Type: orthogonal
    - Source: WebASG
      SourcePosition: E
      Target: ECR
      TargetPosition: W
      TargetArrowHead:
        Type: Open
      Type: orthogonal
    - Source: WebASG
      SourcePosition: E
      Target: CloudWatch
      TargetPosition: W
      TargetArrowHead:
        Type: Open
      Type: orthogonal
    - Source: CloudWatch
      SourcePosition: E
      Target: SNS
      TargetPosition: W
      TargetArrowHead:
        Type: Open
      Type: orthogonal
